/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mastermind2.pkg0;

import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Manuel Cañamaque
 */
public class InicioMain extends javax.swing.JFrame {
    int dificultad=4;    
    
    public void setDificultad(int dificultad){
        this.dificultad = dificultad;
    }
    public int getDificultad(){
        return dificultad;
    }
    /**
     * Creates new form InicioMain
     */
    public InicioMain() {
        initComponents();
        setLocationRelativeTo(null);
        setIconImage(new ImageIcon(getClass().getResource("/imagenes/icon.png")).getImage());
    }   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        boton_Normal = new javax.swing.JButton();
        Boton_Dificil = new javax.swing.JButton();
        boton_Hardcore = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("MasterMind");
        setResizable(false);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/mastermind.jpg"))); // NOI18N

        boton_Normal.setText("Normal");
        boton_Normal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_NormalActionPerformed(evt);
            }
        });

        Boton_Dificil.setText("Dificil");
        Boton_Dificil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton_DificilActionPerformed(evt);
            }
        });

        boton_Hardcore.setText("Hardcore");
        boton_Hardcore.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_HardcoreActionPerformed(evt);
            }
        });

        jLabel2.setText("Bienvenido a Mastermind, elija una dificultad:");

        jButton1.setText("Instrucciones");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(boton_Normal, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, Short.MAX_VALUE)
                        .addComponent(Boton_Dificil, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(boton_Hardcore, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(boton_Normal)
                    .addComponent(Boton_Dificil)
                    .addComponent(boton_Hardcore))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void boton_NormalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_NormalActionPerformed
        setDificultad(4);
        this.setVisible(false);
        MasterMind normal=new MasterMind(dificultad);
        normal.setVisible(true);
    }//GEN-LAST:event_boton_NormalActionPerformed

    private void Boton_DificilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton_DificilActionPerformed
        setDificultad(6);        
        this.setVisible(false); 
        MasterMind dificil=new MasterMind(dificultad);
        dificil.setVisible(true);
    }//GEN-LAST:event_Boton_DificilActionPerformed

    private void boton_HardcoreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_HardcoreActionPerformed
        setDificultad(8);        
        this.setVisible(false);
        MasterMind hardcore=new MasterMind(dificultad);
        hardcore.setVisible(true);
    }//GEN-LAST:event_boton_HardcoreActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        JOptionPane.showMessageDialog(this, "1º Selecciona la dificultad deseada.\n"
                + "   - Normal: 4 Colores y 8 intentos máximo.\n"
                + "       Puntuación máxima: 700000 puntos\n"        
                + "   - Dificil: 6 Colores y 12 intentos máximo.\n"
                + "       Puntuación máxima: 1800000 puntos\n"
                + "   - Hardcore: 8 Colores y 12 intentos máximo.\n"
                + "       Puntuación máxima: 3400000 puntos\n"
                + "2º Pulsa el botón Iniciar Juego y el el tiempo empezara a contar.\n"
                + "3º Rellena la fila de abajo, pulsando en el color deseado\n"
                + " y a continuación en cada uno de los recuadros en blanco.\n"
                + "4º Pulsa el botón Comprobar y los aciertos se mostrarán a la derecha.\n"
                + "5º Repite los pasos 3 y 4 con las filas siguientes, hasta que aciertes la combinación\n"
                + " o te quedes sin intentos.\n"
                + "6º El juego terminará cuando adivines la secuencia secreta o te quedes sin filas.\n"
                + "6º En cualquier momento puedes pulsar el botón Reiniciar Juego para volver al menu.\n\n"
                + "                                            ¡Que se divierta!");
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InicioMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InicioMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InicioMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InicioMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InicioMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Boton_Dificil;
    private javax.swing.JButton boton_Hardcore;
    private javax.swing.JButton boton_Normal;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
